Repository codesquad-members-2024/be-spring-cafe, pull requests merged in 2024-04, with the labels that each got.

#3 [yelly] step-1 회원 가입 및 목록 조회 기능
  build.gradle
  src/main/java/codesquad/springcafe/controller/HomeController.java
  src/main/java/codesquad/springcafe/controller/member/MemberController.java
  src/main/java/codesquad/springcafe/controller/member/ResponseMember.java
  src/main/java/codesquad/springcafe/domain/member/Member.java
  src/main/java/codesquad/springcafe/repository/member/MemberRepository.java
  src/main/java/codesquad/springcafe/repository/member/MemberRepositoryInMemory.java
  src/main/java/codesquad/springcafe/service/member/MemberManager.java
  src/main/java/codesquad/springcafe/service/member/MemberService.java
  src/main/resources/application.properties
  src/main/resources/static/css/styles.css
  src/main/resources/static/index.html
  src/main/resources/static/qna/form.html
  src/main/resources/static/user/login_failed.html
  src/main/resources/static/user/profile.html
  src/main/resources/templates/error/404.html
  src/main/resources/templates/favicon.ico
  src/main/resources/templates/fragment/layout/content.html
  src/main/resources/templates/fragment/layout/header.html
  src/main/resources/templates/fragment/layout/navigation.html
  src/main/resources/templates/home.html
  src/main/resources/templates/members/form.html
  src/main/resources/templates/members/list.html
  src/main/resources/templates/members/login.html
  src/main/resources/templates/members/login_failed.html
  src/main/resources/templates/members/profile.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/test/java/codesquad/springcafe/domain/member/MemberTest.java
  src/test/java/codesquad/springcafe/repository/member/MemberRepositoryTest.java
  src/test/java/codesquad/springcafe/service/member/MemberServiceTest.java
Labels: Step7-1

#4 [Soap] step-1 회원 가입 및 목록 조회 기능
  .gitignore
  build.gradle
  src/main/java/codesquad/springcafe/SpringCafeApplication.java
  src/main/java/codesquad/springcafe/controller/MainController.java
  src/main/java/codesquad/springcafe/controller/UserController.java
  src/main/java/codesquad/springcafe/domain/User.java
  src/main/java/codesquad/springcafe/domain/UserDTO.java
  src/main/java/codesquad/springcafe/repository/MemUserRepository.java
  src/main/java/codesquad/springcafe/repository/UserRepository.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/static/index.html
  src/main/resources/static/qna/form.html
  src/main/resources/static/qna/show.html
  src/main/resources/static/user/form.html
  src/main/resources/static/user/list.html
  src/main/resources/static/user/login.html
  src/main/resources/static/user/login_failed.html
  src/main/resources/static/user/profile.html
  src/main/resources/templates/components/html/header.partial.html
  src/main/resources/templates/components/html/scripts.partial.html
  src/main/resources/templates/components/navbar.partial.html
  src/main/resources/templates/components/qna/answer_template.partial.html
  src/main/resources/templates/components/qna/list.partial.html
  src/main/resources/templates/components/qna/template.partial.html
  src/main/resources/templates/components/user/login_model.partial.html
  src/main/resources/templates/components/user/register_model.partial.html
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
  src/test/java/codesquad/springcafe/MustacheTest.java
Labels: Step7-1

#5 [웨이드] step-1 회원 가입 및 목록 조회 기능
  build.gradle
  src/main/java/codesquad/springcafe/controller/UserController.java
  src/main/java/codesquad/springcafe/domain/User.java
  src/main/java/codesquad/springcafe/repository/UserRepository.java
  src/main/java/codesquad/springcafe/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/static/index.html
  src/main/resources/static/qna/form.html
  src/main/resources/static/qna/show.html
  src/main/resources/static/user/form.html
  src/main/resources/static/user/list.html
  src/main/resources/static/user/login.html
  src/main/resources/static/user/login_failed.html
  src/main/resources/static/user/profile.html
  src/main/resources/templates/fragment/header.html
  src/main/resources/templates/fragment/navbar.html
  src/main/resources/templates/fragment/script.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
Labels: Step7-1

#8 [Alex] Step 1- 회원 가입 및 목록 조회 기능
  build.gradle
  src/main/java/springcafe/SpringCafeApplication.java
  src/main/java/springcafe/controller/UserController.java
  src/main/java/springcafe/dto/UserCreateForm.java
  src/main/java/springcafe/dto/UserDto.java
  src/main/java/springcafe/model/User.java
  src/main/java/springcafe/repository/UserRepository.java
  src/main/java/springcafe/repository/UserRepositoryImpl.java
  src/main/java/springcafe/user/service/UserService.java
  src/main/resources/static/index.html
  src/main/resources/static/qna/form.html
  src/main/resources/static/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
  src/test/java/springcafe/user/UserServiceTest.java
Labels: Step7-1

#11 [데이] step-1 회원 가입 및 목록 조회 기능
  README.md
  build.gradle
  src/main/java/codesquad/springcafe/DB/Database.java
  src/main/java/codesquad/springcafe/controller/UserController.java
  src/main/java/codesquad/springcafe/domain/User.java
  src/main/resources/application.properties
  src/main/resources/logback-spring.xml
  src/main/resources/static/index.html
  src/main/resources/static/qna/form.html
  src/main/resources/static/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
Labels: Step7-1

#12 [제이든] step-1 회원 가입 및 목록 조회 기능
  README.md
  build.gradle
  src/main/java/codesquad/springcafe/main/MainController.java
  src/main/java/codesquad/springcafe/user/User.java
  src/main/java/codesquad/springcafe/user/UserBuilder.java
  src/main/java/codesquad/springcafe/user/UserController.java
  src/main/java/codesquad/springcafe/user/UserDatabase.java
  src/main/java/codesquad/springcafe/user/UserRequestDto.java
  src/main/java/codesquad/springcafe/user/UserSignupDto.java
  src/main/resources/application.properties
  src/main/resources/static/index.html
  src/main/resources/static/qna/form.html
  src/main/resources/static/qna/show.html
  src/main/resources/static/user/form.html
  src/main/resources/static/user/login_failed.html
  src/main/resources/static/user/profile.html
  src/main/resources/templates/index.html
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/layout/headernav.html
  src/main/resources/templates/layout/subbnav.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
  src/test/java/codesquad/springcafe/user/UserBuilderTest.java
  src/test/java/codesquad/springcafe/user/UserDatabaseTest.java
Labels: Step7-1

#15 [미르] Step-1 회원 가입 및 목록 조회 기능
  build.gradle
  src/main/java/codesquad/springcafe/controller/UserController.java
  src/main/java/codesquad/springcafe/database/UserRepository.java
  src/main/java/codesquad/springcafe/model/User.java
  src/main/java/codesquad/springcafe/service/UserService.java
  src/main/resources/static/index.html
  src/main/resources/static/user/form.html
  src/main/resources/static/user/login_failed.html
  src/main/resources/static/user/profile.html
  src/main/resources/static/users/login.html
  src/main/resources/static/users/login_failed.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/headernav.html
  src/main/resources/templates/fragments/subnav.html
  src/main/resources/templates/users/form.html
  src/main/resources/templates/users/list.html
  src/main/resources/templates/users/profile.html
Labels: Step7-1

#17 [코리] Step-1 회원 가입 및 목록 조회 기능
  .gitignore
  build.gradle
  src/main/java/codesquad/springcafe/controller/HomeController.java
  src/main/java/codesquad/springcafe/controller/UserController.java
  src/main/java/codesquad/springcafe/dto/UserProfileDto.java
  src/main/java/codesquad/springcafe/model/User.java
  src/main/java/codesquad/springcafe/repository/UserRepository.java
  src/main/java/codesquad/springcafe/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/static/qna/form.html
  src/main/resources/static/user/form.html
  src/main/resources/static/user/login.html
  src/main/resources/static/user/login_failed.html
  src/main/resources/static/user/profile.html
  src/main/resources/templates/fragments/base.html
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
  src/test/java/codesquad/springcafe/controller/UserControllerTest.java
  src/test/java/codesquad/springcafe/repository/UserRepositoryTest.java
  src/test/java/codesquad/springcafe/service/UserServiceTest.java
Labels: Step7-1

#19 [yelly] step-2 글 쓰기 기능 구현
  src/main/java/codesquad/springcafe/controller/HomeController.java
  src/main/java/codesquad/springcafe/controller/article/ArticleController.java
  src/main/java/codesquad/springcafe/controller/article/ArticleForm.java
  src/main/java/codesquad/springcafe/controller/member/MemberController.java
  src/main/java/codesquad/springcafe/controller/member/UpdateMember.java
  src/main/java/codesquad/springcafe/domain/article/Article.java
  src/main/java/codesquad/springcafe/repository/article/ArticleRepository.java
  src/main/java/codesquad/springcafe/repository/article/ArticleRepositoryInMemory.java
  src/main/java/codesquad/springcafe/repository/member/MemberRepository.java
  src/main/java/codesquad/springcafe/repository/member/MemberRepositoryInMemory.java
  src/main/java/codesquad/springcafe/service/article/ArticleManager.java
  src/main/java/codesquad/springcafe/service/article/ArticleService.java
  src/main/java/codesquad/springcafe/service/member/MemberManager.java
  src/main/java/codesquad/springcafe/service/member/MemberService.java
  src/main/resources/application.properties
  src/main/resources/templates/home.html
  src/main/resources/templates/members/list.html
  src/main/resources/templates/members/updateForm.html
  src/main/resources/templates/qna/detail.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/test/java/codesquad/springcafe/controller/article/ArticleControllerTest.java
  src/test/java/codesquad/springcafe/controller/article/ArticleFormTest.java
  src/test/java/codesquad/springcafe/controller/member/UpdateMemberTest.java
  src/test/java/codesquad/springcafe/domain/article/ArticleTest.java
  src/test/java/codesquad/springcafe/repository/article/ArticleRepositoryTest.java
  src/test/java/codesquad/springcafe/repository/member/MemberRepositoryTest.java
  src/test/java/codesquad/springcafe/service/article/ArticleServiceTest.java
  src/test/java/codesquad/springcafe/service/member/MemberServiceTest.java
Labels: Step7-2

#20 [Soap] Step3 : H2 DB 연결 , EC2 배포
  HELP.md
  build.gradle
  src/main/java/codesquad/springcafe/AppConfig.java
  src/main/java/codesquad/springcafe/article/Article.java
  src/main/java/codesquad/springcafe/article/ArticleController.java
  src/main/java/codesquad/springcafe/article/ArticlePostReq.java
  src/main/java/codesquad/springcafe/article/repository/ArticleConsts.java
  src/main/java/codesquad/springcafe/article/repository/ArticleRepository.java
  src/main/java/codesquad/springcafe/article/repository/H2ArticleRepository.java
  src/main/java/codesquad/springcafe/article/repository/MemoryArticleRepository.java
  src/main/java/codesquad/springcafe/user/Alert.java
  src/main/java/codesquad/springcafe/user/LoginCheckInterceptor.java
  src/main/java/codesquad/springcafe/user/User.java
  src/main/java/codesquad/springcafe/user/UserController.java
  src/main/java/codesquad/springcafe/user/UserService.java
  src/main/java/codesquad/springcafe/user/repository/H2UserRepository.java
  src/main/resources/application.yml
  src/main/resources/banner.txt
  src/main/resources/templates/components/navbar.partial.html
  src/main/resources/templates/components/qna/comment.partial.html
  src/main/resources/templates/components/qna/list.partial.html
  src/main/resources/templates/components/qna/list_dummy.partial.html
  src/main/resources/templates/components/qna/template.partial.html
  src/main/resources/templates/components/user/login_model.partial.html
  src/main/resources/templates/components/user/register_model.partial.html
  src/main/resources/templates/components/user/userNameBar.partial.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/profile.html
  src/main/resources/templates/user/update_form.html
Labels: Step7-3

#22 [제이든] step-2 글쓰기 및 회원정보 수정 기능 구현
  README.md
  src/main/java/codesquad/springcafe/article/Article.java
  src/main/java/codesquad/springcafe/article/ArticleBuilder.java
  src/main/java/codesquad/springcafe/article/ArticleController.java
  src/main/java/codesquad/springcafe/article/ArticleCreateDto.java
  src/main/java/codesquad/springcafe/article/ArticleDatabase.java
  src/main/java/codesquad/springcafe/main/MainController.java
  src/main/java/codesquad/springcafe/security/PasswordEncryptor.java
  src/main/java/codesquad/springcafe/user/User.java
  src/main/java/codesquad/springcafe/user/UserController.java
  src/main/java/codesquad/springcafe/user/UserDatabase.java
  src/main/java/codesquad/springcafe/user/UserSignupDto.java
  src/main/java/codesquad/springcafe/user/UserUpdateDto.java
  src/main/resources/application.properties
  src/main/resources/static/qna/form.html
  src/main/resources/static/qna/show.html
  src/main/resources/templates/article/form.html
  src/main/resources/templates/article/show.html
  src/main/resources/templates/index.html
  src/main/resources/templates/layout/subbnav.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/update_form.html
  src/test/java/codesquad/springcafe/article/ArticleCreateDtoTest.java
  src/test/java/codesquad/springcafe/article/ArticleDatabaseTest.java
  src/test/java/codesquad/springcafe/security/PasswordEncryptorTest.java
Labels: Step7-2

#28 [yelly] step-3 DB에 저장하기
  build.gradle
  src/main/java/codesquad/springcafe/controller/article/ArticleController.java
  src/main/java/codesquad/springcafe/repository/article/ArticleRepositoryH2.java
  src/main/java/codesquad/springcafe/repository/article/sql/create.sql
  src/main/java/codesquad/springcafe/repository/member/MemberRepositoryH2.java
  src/main/java/codesquad/springcafe/repository/member/sql/create.sql
  src/main/resources/application.properties
  src/main/resources/schema.sql
  src/main/resources/templates/home.html
  src/main/resources/templates/qna/detail.html
  src/test/java/codesquad/springcafe/controller/article/ArticleControllerTest.java
  src/test/java/codesquad/springcafe/repository/article/ArticleRepositoryH2Test.java
  src/test/java/codesquad/springcafe/repository/article/ArticleRepositoryInMemoryTest.java
  src/test/java/codesquad/springcafe/repository/member/MemberRepositoryH2Test.java
  src/test/java/codesquad/springcafe/repository/member/MemberRepositoryInMemoryTest.java
Labels: Step7-3

#30 [Daniel] step-1 회원 가입 및 목록 조회 기능
  build.gradle
  src/main/java/codesquad/springcafe/DB/UserDatabase.java
  src/main/java/codesquad/springcafe/MvcConfig.java
  src/main/java/codesquad/springcafe/controller/UserController.java
  src/main/java/codesquad/springcafe/domain/User.java
  src/main/resources/application.properties
  src/main/resources/static/css/index.css
  src/main/resources/static/css/post/form.css
  src/main/resources/static/css/post/show.css
  src/main/resources/static/css/reset.css
  src/main/resources/static/css/user/form.css
  src/main/resources/static/css/user/list.css
  src/main/resources/static/css/user/login.css
  src/main/resources/static/css/user/login_success.css
  src/main/resources/static/images/KakaoCI.png
  src/main/resources/static/images/user.png
  src/main/resources/static/index.html
  src/main/resources/static/qna/form.html
  src/main/resources/static/qna/show.html
  src/main/resources/static/user/form.html
  src/main/resources/static/user/login.html
  src/main/resources/static/user/login_failed.html
  src/main/resources/static/user/profile.html
  src/main/resources/templates/favicon.ico
  src/main/resources/templates/main.html
  src/main/resources/templates/post/form.html
  src/main/resources/templates/post/show.html
  src/main/resources/templates/repeatedHtml/basic_button.html
  src/main/resources/templates/repeatedHtml/head_data.html
  src/main/resources/templates/repeatedHtml/navbar_header.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/login_success.html
  src/main/resources/templates/user/profile.html
Labels: Step7-1

#31 [그로밋] step-1 회원 가입 및 목록 조회 기능
  .gitignore
  build.gradle
  src/main/java/codesquad/springcafe/MvcConfig.java
  src/main/java/codesquad/springcafe/user/User.java
  src/main/java/codesquad/springcafe/user/UserController.java
  src/main/java/codesquad/springcafe/user/UserCreationDTO.java
  src/main/java/codesquad/springcafe/user/UserDTO.java
  src/main/java/codesquad/springcafe/user/UserRepository.java
  src/main/resources/application.properties
  src/main/resources/static/qna/form.html
  src/main/resources/static/qna/show.html
  src/main/resources/static/user/form.html
  src/main/resources/static/user/login.html
  src/main/resources/static/user/login_failed.html
  src/main/resources/static/user/profile.html
  src/main/resources/templates/index.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
  src/main/resources/templates/view/footer.html
  src/main/resources/templates/view/head.html
  src/main/resources/templates/view/nav.html
Labels: Step7-1

#32 [코리] Step-2 글 쓰기 기능 구현
  src/main/java/codesquad/springcafe/controller/ArticleController.java
  src/main/java/codesquad/springcafe/controller/HomeController.java
  src/main/java/codesquad/springcafe/controller/UserController.java
  src/main/java/codesquad/springcafe/dto/ArticleRequestDto.java
  src/main/java/codesquad/springcafe/dto/UserUpdateDto.java
  src/main/java/codesquad/springcafe/model/Article.java
  src/main/java/codesquad/springcafe/model/User.java
  src/main/java/codesquad/springcafe/repository/ArticleRepository.java
  src/main/java/codesquad/springcafe/repository/UserRepository.java
  src/main/java/codesquad/springcafe/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/templates/fragments/base.html
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/updateForm.html
  src/test/java/codesquad/springcafe/controller/ArticleControllerTest.java
  src/test/java/codesquad/springcafe/controller/UserControllerTest.java
  src/test/java/codesquad/springcafe/repository/ArticleRepositoryTest.java
  src/test/java/codesquad/springcafe/service/UserServiceTest.java
Labels: Step7-2

#38 [Jin] Step7-1 회원 가입 및 목록 조회 기능
  build.gradle
  src/main/java/codesquad/springcafe/config/MvcConfiguration.java
  src/main/java/codesquad/springcafe/controller/HomeController.java
  src/main/java/codesquad/springcafe/controller/MemberController.java
  src/main/java/codesquad/springcafe/controller/MemberForm.java
  src/main/java/codesquad/springcafe/domain/Member.java
  src/main/java/codesquad/springcafe/domain/Profile.java
  src/main/java/codesquad/springcafe/repository/MemberRepository.java
  src/main/java/codesquad/springcafe/repository/MemoryMemberRepository.java
  src/main/java/codesquad/springcafe/repository/MemoryProfileRepository.java
  src/main/java/codesquad/springcafe/repository/ProfileRepository.java
  src/main/java/codesquad/springcafe/service/MemberService.java
  src/main/resources/static/index.html
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
Labels: Step7-1

#39 [주주] Step-1 회원 가입 및 목록 조회 기능
  README.md
  build.gradle
  src/main/java/codesquad/springcafe/SpringCafeApplication.java
  src/main/java/codesquad/springcafe/controller/UserController.java
  src/main/java/codesquad/springcafe/model/User.java
  src/main/java/codesquad/springcafe/repository/UserRepository.java
  src/main/java/codesquad/springcafe/service/UserService.java
  src/main/resources/static/index.html
  src/main/resources/static/qna/form.html
  src/main/resources/static/user/form.html
  src/main/resources/static/user/login.html
  src/main/resources/static/user/login_failed.html
  src/main/resources/static/user/profile.html
  src/main/resources/templates/fragment/header.html
  src/main/resources/templates/fragment/navbar.html
  src/main/resources/templates/fragment/script.html
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/users/form.html
  src/main/resources/templates/users/list.html
  src/main/resources/templates/users/login.html
  src/main/resources/templates/users/login_failed.html
  src/main/resources/templates/users/profile.html
Labels: Step7-1

#43 [애셔] step-1 회원 가입 및 목록 조회 기능
  build.gradle
  src/main/java/codesquad/springcafe/web/SpringConfig.java
  src/main/java/codesquad/springcafe/web/controller/UserController.java
  src/main/java/codesquad/springcafe/web/domain/User.java
  src/main/java/codesquad/springcafe/web/repository/MemoryUserRepository.java
  src/main/java/codesquad/springcafe/web/repository/UserRepository.java
  src/main/java/codesquad/springcafe/web/service/UserService.java
  src/main/resources/static/index.html
  src/main/resources/static/qna/form.html
  src/main/resources/static/qna/show.html
  src/main/resources/static/user/form.html
  src/main/resources/static/user/login.html
  src/main/resources/static/user/login_failed.html
  src/main/resources/static/user/profile.html
  src/main/resources/templates/fragments/base.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/profile.html
Labels: Step7-1

#44 [Alex] Step 2- 글쓰기 기능 구현
  build.gradle
  src/main/java/springcafe/article/controller/ArticleController.java
  src/main/java/springcafe/article/model/Article.java
  src/main/java/springcafe/article/repository/ArticleRepository.java
  src/main/java/springcafe/article/repository/ArticleRepositoryImpl.java
  src/main/java/springcafe/article/service/ArticleService.java
  src/main/java/springcafe/config/MvcConfig.java
  src/main/java/springcafe/controller/UserController.java
  src/main/java/springcafe/dto/UserCreateForm.java
  src/main/java/springcafe/model/User.java
  src/main/java/springcafe/user/controller/UserController.java
  src/main/java/springcafe/user/dto/UserCreateForm.java
  src/main/java/springcafe/user/dto/UserDto.java
  src/main/java/springcafe/user/model/User.java
  src/main/java/springcafe/user/repository/UserRepository.java
  src/main/java/springcafe/user/repository/UserRepositoryImpl.java
  src/main/java/springcafe/user/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/static/index.html
  src/main/resources/static/login.html
  src/main/resources/static/qna/show.html
  src/main/resources/static/signup.html
  src/main/resources/static/updateForm.html
  src/main/resources/templates/fragments/form_errors.html
  src/main/resources/templates/fragments/head.html
  src/main/resources/templates/fragments/navbar.html
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
  src/main/resources/templates/user/updateform.html
  src/test/java/springcafe/user/UserServiceTest.java
Labels: Step7-2

#46 [다오] Step-2 글 쓰기 기능 구현
  README.md
  src/main/java/codesquad/springcafe/Article.java
  src/main/java/codesquad/springcafe/ArticleController.java
  src/main/java/codesquad/springcafe/IndexController.java
  src/main/java/codesquad/springcafe/User.java
  src/main/java/codesquad/springcafe/UserController.java
  src/main/java/codesquad/springcafe/config/MvcConfig.java
  src/main/java/codesquad/springcafe/database/ArticleDatabase.java
  src/main/resources/application.properties
  src/main/resources/static/qna/form.html
  src/main/resources/templates/index.html
  src/main/resources/templates/part/part_header.html
  src/main/resources/templates/part/part_script.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/updateForm.html
Labels: Step7-2

#47 [망고] step-1 회원 가입 및 목록 조회 기능
  build.gradle
  src/main/java/codesquad/springcafe/AutoAppConfig.java
  src/main/java/codesquad/springcafe/controller/UserController.java
  src/main/java/codesquad/springcafe/dto/User.java
  src/main/java/codesquad/springcafe/repository/MemoryUserRepository.java
  src/main/java/codesquad/springcafe/repository/UserRepository.java
  src/main/java/codesquad/springcafe/service/UserService.java
  src/main/java/codesquad/springcafe/service/UserServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/templates/index.mustache
  src/main/resources/templates/users/form.mustache
  src/main/resources/templates/users/list.mustache
  src/main/resources/templates/users/profile.mustache
  src/test/java/codesquad/springcafe/beanfind/ApplicationContextInfoTest.java
  src/test/java/codesquad/springcafe/service/UserServiceImplTest.java
Labels: Step7-1

#54 [제이든] step-3: DB저장하기
  build.gradle
  src/main/java/codesquad/springcafe/article/Article.java
  src/main/java/codesquad/springcafe/article/ArticleBuilder.java
  src/main/java/codesquad/springcafe/article/ArticleController.java
  src/main/java/codesquad/springcafe/article/ArticleCreateDto.java
  src/main/java/codesquad/springcafe/article/ArticleRowMapper.java
  src/main/java/codesquad/springcafe/article/database/ArticleDatabase.java
  src/main/java/codesquad/springcafe/article/database/ArticleH2Database.java
  src/main/java/codesquad/springcafe/article/database/ArticleInMemoryDatabase.java
  src/main/java/codesquad/springcafe/main/MainController.java
  src/main/java/codesquad/springcafe/user/User.java
  src/main/java/codesquad/springcafe/user/UserController.java
  src/main/java/codesquad/springcafe/user/UserRowMapper.java
  src/main/java/codesquad/springcafe/user/database/UserDatabase.java
  src/main/java/codesquad/springcafe/user/database/UserH2Database.java
  src/main/java/codesquad/springcafe/user/database/UserInMemoryDatabase.java
  src/main/resources/application.properties
  src/test/java/codesquad/springcafe/article/ArticleInMemoryDatabaseTest.java
  src/test/java/codesquad/springcafe/main/MainControllerTest.java
  src/test/java/codesquad/springcafe/user/UserInMemoryDatabaseTest.java
Labels: Step7-3

#58 [senna] - Step1
  build.gradle
  src/main/java/codesquad/springcafe/database/Database.java
  src/main/java/codesquad/springcafe/database/MemoryDatabase.java
  src/main/java/codesquad/springcafe/database/firstcollection/Users.java
  src/main/java/codesquad/springcafe/exceptions/NoSuchUserException.java
  src/main/java/codesquad/springcafe/user/UserController.java
  src/main/java/codesquad/springcafe/user/domain/User.java
  src/main/java/codesquad/springcafe/user/respository/UserRepository.java
  src/main/resources/static/index.html
  src/main/resources/static/qna/form.html
  src/main/resources/static/qna/show.html
  src/main/resources/static/user/form.html
  src/main/resources/static/user/login.html
  src/main/resources/static/user/login_failed.html
  src/main/resources/static/user/no_user.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/profile.html
Labels: Step7-1

#59 [eddy] step-3 DB에 저장하기
  README.md
  build.gradle
  src/main/java/codesquad/springcafe/Domain/Post.java
  src/main/java/codesquad/springcafe/Domain/User.java
  src/main/java/codesquad/springcafe/MvcConfig.java
  src/main/java/codesquad/springcafe/Repository/PostRepository.java
  src/main/java/codesquad/springcafe/Repository/PostRepositoryImpl.java
  src/main/java/codesquad/springcafe/Repository/PostRepositoryJDBC.java
  src/main/java/codesquad/springcafe/Repository/UserRepositoryImpl.java
  src/main/java/codesquad/springcafe/Repository/UserRepositoryJDBC.java
  src/main/resources/application.properties
  src/main/resources/sql/ddl.sql
  src/test/java/codesquad/springcafe/Service/UserServiceTest.java
  src/test/java/codesquad/springcafe/test.http
Labels: Step7-3

#65 [주주] step-2 글 쓰기 기능 구현, 회원정보 수정 기능 구현
  src/main/java/codesquad/springcafe/controller/ArticleController.java
  src/main/java/codesquad/springcafe/controller/UserController.java
  src/main/java/codesquad/springcafe/http/request.http
  src/main/java/codesquad/springcafe/model/Article.java
  src/main/java/codesquad/springcafe/repository/ArticleRepository.java
  src/main/java/codesquad/springcafe/repository/UserRepository.java
  src/main/java/codesquad/springcafe/service/ArticleService.java
  src/main/java/codesquad/springcafe/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/templates/fragment/navbar.html
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/users/list.html
  src/main/resources/templates/users/updateForm.html
Labels: Step7-2

#66 [샤피] 글 쓰기 기능 구현, 회원정보 수정 기능 구현, 로그인 기능 구현
  README.md
  build.gradle
  docs/step2-study.md
  src/main/java/codesquad/springcafe/domain/question/controller/QuestionController.java
  src/main/java/codesquad/springcafe/domain/question/data/QuestionListResponse.java
  src/main/java/codesquad/springcafe/domain/question/data/QuestionPostRequest.java
  src/main/java/codesquad/springcafe/domain/question/data/QuestionResponse.java
  src/main/java/codesquad/springcafe/domain/question/model/Question.java
  src/main/java/codesquad/springcafe/domain/question/model/QuestionRepository.java
  src/main/java/codesquad/springcafe/domain/question/model/QuestionRepositoryLocal.java
  src/main/java/codesquad/springcafe/domain/question/service/QuestionService.java
  src/main/java/codesquad/springcafe/domain/user/controller/UserController.java
  src/main/java/codesquad/springcafe/domain/user/data/UserJoinRequest.java
  src/main/java/codesquad/springcafe/domain/user/data/UserListResponse.java
  src/main/java/codesquad/springcafe/domain/user/data/UserLoginRequest.java
  src/main/java/codesquad/springcafe/domain/user/data/UserResponse.java
  src/main/java/codesquad/springcafe/domain/user/data/UserUpdateRequest.java
  src/main/java/codesquad/springcafe/domain/user/model/User.java
  src/main/java/codesquad/springcafe/domain/user/model/UserRepository.java
  src/main/java/codesquad/springcafe/domain/user/model/UserRepositoryLocal.java
  src/main/java/codesquad/springcafe/domain/user/service/UserService.java
  src/main/java/codesquad/springcafe/global/config/AppConfig.java
  src/main/java/codesquad/springcafe/global/filter/CacheControlFilter.java
  src/main/java/codesquad/springcafe/global/interceptor/AfterAuthorizeInterceptor.java
  src/main/java/codesquad/springcafe/global/interceptor/AuthenticationInterceptor.java
  src/main/java/codesquad/springcafe/global/interceptor/CsrfTokenIntercetor.java
  src/main/java/codesquad/springcafe/global/security/PasswordEncoder.java
  src/main/resources/config/application.properties
  src/main/resources/static/css/post/show.css
  src/main/resources/static/css/user/profile.css
  src/main/resources/static/js/global.js
  src/main/resources/templates/base/error/error.html
  src/main/resources/templates/base/part/menu.html
  src/main/resources/templates/base/part/navbar.html
  src/main/resources/templates/base/part/navbar_toMain.html
  src/main/resources/templates/base/user/user_profile_link.html
  src/main/resources/templates/error/server_error.html
  src/main/resources/templates/index.html
  src/main/resources/templates/post/form.html
  src/main/resources/templates/post/show.html
  src/main/resources/templates/user/edit_form.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/profile.html
  src/main/resources/templates/user/registration_success.html
  src/test/http/userTest.http
  src/test/java/codesquad/springcafe/domain/user/controller/UserControllerTest.java
Labels: Step7-2, Step8-1

#68 [Sid] Step2 글 쓰기 기능 , 회원 정보 수정 기능
  src/main/java/codesquad/springcafe/ExceptionHandlerAdvisor.java
  src/main/java/codesquad/springcafe/UserController.java
  src/main/java/codesquad/springcafe/controller/ArticleController.java
  src/main/java/codesquad/springcafe/controller/HomeController.java
  src/main/java/codesquad/springcafe/controller/UserController.java
  src/main/java/codesquad/springcafe/db/ArticleDatabase.java
  src/main/java/codesquad/springcafe/db/UserDatabase.java
  src/main/java/codesquad/springcafe/model/Article.java
  src/main/java/codesquad/springcafe/model/User.java
  src/main/resources/application.properties
  src/main/resources/static/article/form.html
  src/main/resources/static/css/article/form.css
  src/main/resources/static/css/article/show.css
  src/main/resources/static/css/component/post_btn.css
  src/main/resources/static/css/index.css
  src/main/resources/static/index.html
  src/main/resources/static/post/show.html
  src/main/resources/static/user/form.html
  src/main/resources/static/user/login.html
  src/main/resources/static/user/login_success.html
  src/main/resources/templates/article/list.html
  src/main/resources/templates/article/show.html
  src/main/resources/templates/layout/non_login_footer.html
  src/main/resources/templates/layout/non_login_navbar.html
  src/main/resources/templates/users/list.html
  src/main/resources/templates/users/profile.html
  src/main/resources/templates/users/updateForm.html
  src/test/java/codesquad/springcafe/controller/ArticleControllerTest.java
  src/test/java/codesquad/springcafe/controller/UserControllerTest.java
Labels: Step7-2

#69 [실브] step-2 글 쓰기 기능 구현
  build.gradle
  src/main/java/codesquad/springcafe/SpringCafeApplication.java
  src/main/java/codesquad/springcafe/config/MvcConfig.java
  src/main/java/codesquad/springcafe/config/SecurityConfig.java
  src/main/java/codesquad/springcafe/config/WebMvcConfigurer.java
  src/main/java/codesquad/springcafe/controller/ArticleController.java
  src/main/java/codesquad/springcafe/controller/UserController.java
  src/main/java/codesquad/springcafe/dto/article/ArticleInfoDTO.java
  src/main/java/codesquad/springcafe/dto/article/ArticleUpdateDTO.java
  src/main/java/codesquad/springcafe/dto/article/UploadDTO.java
  src/main/java/codesquad/springcafe/dto/user/SignUpDTO.java
  src/main/java/codesquad/springcafe/dto/user/UserInfoDTO.java
  src/main/java/codesquad/springcafe/dto/user/UserUpdateDTO.java
  src/main/java/codesquad/springcafe/model/Article.java
  src/main/java/codesquad/springcafe/model/Reply.java
  src/main/java/codesquad/springcafe/model/User.java
  src/main/java/codesquad/springcafe/repository/article/ArticleRepository.java
  src/main/java/codesquad/springcafe/repository/article/MemoryArticleRepository.java
  src/main/java/codesquad/springcafe/repository/user/MemoryUserRepository.java
  src/main/java/codesquad/springcafe/repository/user/UserRepository.java
  src/main/java/codesquad/springcafe/service/ArticleService.java
  src/main/java/codesquad/springcafe/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/static/index.html
  src/main/resources/static/qna/show.html
  src/main/resources/static/user/form.html
  src/main/resources/static/user/list.html
  src/main/resources/static/user/login.html
  src/main/resources/static/user/login_failed.html
  src/main/resources/static/user/profile.html
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/loginBeforeUpdate.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
  src/main/resources/templates/user/updateForm.html
Labels: Step7-2

#72 [그로밋] step-3 DB저장, 배포
  build.gradle
  src/main/java/codesquad/springcafe/article/Article.java
  src/main/java/codesquad/springcafe/article/ArticleController.java
  src/main/java/codesquad/springcafe/article/ArticleCraetionDto.java
  src/main/java/codesquad/springcafe/article/ArticleDao.java
  src/main/java/codesquad/springcafe/article/ArticleRepository.java
  src/main/java/codesquad/springcafe/article/dao/ArticleH2Dao.java
  src/main/java/codesquad/springcafe/article/dao/ArticleMemoryDao.java
  src/main/java/codesquad/springcafe/user/User.java
  src/main/java/codesquad/springcafe/user/UserController.java
  src/main/java/codesquad/springcafe/user/UserDao.java
  src/main/java/codesquad/springcafe/user/UserDto.java
  src/main/java/codesquad/springcafe/user/UserMapper.java
  src/main/java/codesquad/springcafe/user/UserViewDto.java
  src/main/java/codesquad/springcafe/user/dao/UserH2Dao.java
  src/main/java/codesquad/springcafe/user/dao/UserMemoryDao.java
  src/main/resources/application.properties
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/profile.html
Labels: Step7-3

#73 [이브이] step-3 DB에 저장하기
  build.gradle
  src/main/java/codesquad/springcafe/controller/ArticleController.java
  src/main/java/codesquad/springcafe/controller/HomeController.java
  src/main/java/codesquad/springcafe/controller/UserController.java
  src/main/java/codesquad/springcafe/domain/Article.java
  src/main/java/codesquad/springcafe/domain/User.java
  src/main/java/codesquad/springcafe/dto/ArticleDto.java
  src/main/java/codesquad/springcafe/repository/article/ArticleRepository.java
  src/main/java/codesquad/springcafe/repository/article/ArticleRepositoryInterface.java
  src/main/java/codesquad/springcafe/repository/article/JdbcArticleRepository.java
  src/main/java/codesquad/springcafe/repository/article/MemoryArticleRepository.java
  src/main/java/codesquad/springcafe/repository/user/JdbcUserRepository.java
  src/main/java/codesquad/springcafe/repository/user/MemoryUserRepository.java
  src/main/java/codesquad/springcafe/repository/user/UserRepository.java
  src/main/java/codesquad/springcafe/repository/user/UserRepositoryInterface.java
  src/main/resources/application.properties
  src/main/resources/templates/article/show.html
  src/main/resources/templates/index.html
  src/main/sql/article.sql
  src/main/sql/user.sql
Labels: Step7-3

#77 [웨이드] step-3 DB에 저장하기
  build.gradle
  src/main/java/codesquad/springcafe/domain/article/Article.java
  src/main/java/codesquad/springcafe/domain/article/ArticleRepository.java
  src/main/java/codesquad/springcafe/domain/article/JdbcArticleRepository.java
  src/main/java/codesquad/springcafe/domain/article/MemoryArticleRepository.java
  src/main/java/codesquad/springcafe/domain/user/JdbcUserRepository.java
  src/main/java/codesquad/springcafe/domain/user/MemoryUserRepository.java
  src/main/java/codesquad/springcafe/domain/user/User.java
  src/main/java/codesquad/springcafe/domain/user/UserRepository.java
  src/main/java/codesquad/springcafe/service/ArticleService.java
  src/main/java/codesquad/springcafe/service/UserService.java
  src/main/java/codesquad/springcafe/web/controller/ArticleController.java
  src/main/java/codesquad/springcafe/web/controller/UserController.java
  src/main/java/codesquad/springcafe/web/dto/ArticleCreateDto.java
  src/main/java/codesquad/springcafe/web/dto/UserCreateDto.java
  src/main/java/codesquad/springcafe/web/dto/UserUpdateDto.java
  src/main/java/codesquad/springcafe/web/validation/ArticleCreateValidator.java
  src/main/java/codesquad/springcafe/web/validation/UserCreateValidator.java
  src/main/java/codesquad/springcafe/web/validation/UserUpdateValidator.java
  src/main/resources/application.properties
  src/main/resources/templates/fragment/navbar.html
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/updateForm.html
Labels: Step7-3

#78 [Alex] Step 4-로그인 구현
  src/main/java/springcafe/user/controller/ErrorController.java
  src/main/java/springcafe/user/controller/UserController.java
  src/main/java/springcafe/user/dto/ChageInfoForm.java
  src/main/java/springcafe/user/dto/UserCreateForm.java
  src/main/java/springcafe/user/exception/UserNotFoundException.java
  src/main/java/springcafe/user/exception/WrongIdPasswordException.java
  src/main/java/springcafe/user/exception/WrongPasswordException.java
  src/main/java/springcafe/user/login/controller/LoginController.java
  src/main/java/springcafe/user/login/dto/LoginCommand.java
  src/main/java/springcafe/user/login/security/PasswordHashing.java
  src/main/java/springcafe/user/login/service/LoginService.java
  src/main/java/springcafe/user/repository/H2UserDao.java
  src/main/java/springcafe/user/repository/UserDao.java
  src/main/java/springcafe/user/service/UserService.java
  src/main/resources/static/updateForm.html
  src/main/resources/templates/fragments/navbar.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/update.html
Labels: Step8-1

#82 [실브] Step-3 DB에 저장하기
  build.gradle
  src/main/java/codesquad/springcafe/config/SecurityConfig.java
  src/main/java/codesquad/springcafe/controller/ArticleController.java
  src/main/java/codesquad/springcafe/controller/UserController.java
  src/main/java/codesquad/springcafe/dto/article/ArticleInfoDTO.java
  src/main/java/codesquad/springcafe/dto/article/ArticleUpdateDTO.java
  src/main/java/codesquad/springcafe/dto/article/UploadDTO.java
  src/main/java/codesquad/springcafe/dto/user/SignUpDTO.java
  src/main/java/codesquad/springcafe/dto/user/UserUpdateDTO.java
  src/main/java/codesquad/springcafe/model/Article.java
  src/main/java/codesquad/springcafe/model/Reply.java
  src/main/java/codesquad/springcafe/model/User.java
  src/main/java/codesquad/springcafe/repository/article/ArticleRepository.java
  src/main/java/codesquad/springcafe/repository/article/JdbcArticleRepository.java
  src/main/java/codesquad/springcafe/repository/article/MemoryArticleRepository.java
  src/main/java/codesquad/springcafe/repository/user/JdbcUserRepository.java
  src/main/java/codesquad/springcafe/repository/user/MemoryUserRepository.java
  src/main/java/codesquad/springcafe/service/ArticleService.java
  src/main/java/codesquad/springcafe/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/schema.sql
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
Labels: Step7-3

#83 [이브이] step-4 로그인 구현
  src/main/java/codesquad/springcafe/config/WebConfig.java
  src/main/java/codesquad/springcafe/controller/ArticleController.java
  src/main/java/codesquad/springcafe/controller/UserController.java
  src/main/java/codesquad/springcafe/domain/User.java
  src/main/java/codesquad/springcafe/interceptor/AuthorizationInterceptor.java
  src/main/java/codesquad/springcafe/repository/article/JdbcArticleRepository.java
  src/main/java/codesquad/springcafe/repository/article/MemoryArticleRepository.java
  src/main/java/codesquad/springcafe/repository/user/JdbcUserRepository.java
  src/main/java/codesquad/springcafe/repository/user/MemoryUserRepository.java
  src/main/resources/templates/article/create.html
  src/main/resources/templates/article/show.html
  src/main/resources/templates/fragments/main.html
  src/main/resources/templates/fragments/nav.html
  src/main/resources/templates/index.html
  src/main/resources/templates/user/create.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_success.html
  src/main/resources/templates/user/update.html
  src/main/sql/article.sql
  src/main/sql/user.sql
  src/main/sql/users.sql
Labels: Step8-1

#87 [Daniel] step-3 DB에 저장하기
  build.gradle
  src/main/java/codesquad/springcafe/DB/ArticleDatabase.java
  src/main/java/codesquad/springcafe/DB/UserDatabase.java
  src/main/java/codesquad/springcafe/MvcConfig.java
  src/main/java/codesquad/springcafe/controller/ArticleController.java
  src/main/java/codesquad/springcafe/controller/UserController.java
  src/main/java/codesquad/springcafe/database/article/ArticleDatabase.java
  src/main/java/codesquad/springcafe/database/article/H2ArticleDatabase.java
  src/main/java/codesquad/springcafe/database/article/MemoryArticleDatabase.java
  src/main/java/codesquad/springcafe/database/user/H2UserDatabase.java
  src/main/java/codesquad/springcafe/database/user/MemoryUserDatabase.java
  src/main/java/codesquad/springcafe/database/user/UserDatabase.java
  src/main/java/codesquad/springcafe/domain/Article.java
  src/main/java/codesquad/springcafe/domain/UpdatedUser.java
  src/main/java/codesquad/springcafe/domain/User.java
  src/main/java/codesquad/springcafe/dto/ArticleCreateDto.java
  src/main/resources/application.properties
  src/main/resources/templates/article/form.html
  src/main/resources/templates/article/show.html
  src/main/resources/templates/main.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login_success.html
  src/main/resources/templates/user/profile.html
  src/main/resources/templates/user/update_form.html
Labels: Step7-3

#89 [그로밋] step-4 로그인 기능 구현
  build.gradle
  src/main/java/codesquad/springcafe/MvcConfig.java
  src/main/java/codesquad/springcafe/user/User.java
  src/main/java/codesquad/springcafe/user/UserController.java
  src/main/java/codesquad/springcafe/user/UserDao.java
  src/main/java/codesquad/springcafe/user/UserMapper.java
  src/main/java/codesquad/springcafe/user/UserService.java
  src/main/java/codesquad/springcafe/user/UserViewDto.java
  src/main/java/codesquad/springcafe/user/dao/UserH2Dao.java
  src/main/java/codesquad/springcafe/user/dao/UserMemoryDao.java
  src/main/java/codesquad/springcafe/user/dto/UserCreationDto.java
  src/main/java/codesquad/springcafe/user/dto/UserInfoEditRequestDto.java
  src/main/java/codesquad/springcafe/user/dto/UserViewDto.java
  src/main/resources/application.properties
  src/main/resources/static/user/updateFailed.html
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
  src/main/resources/templates/user/updateForm.html
  src/main/resources/templates/view/nav.html
Labels: Step8-1

#91 [Jin] step7-2 글 쓰기 기능 구현
  build.gradle
  src/main/java/codesquad/springcafe/config/MvcConfiguration.java
  src/main/java/codesquad/springcafe/controller/ArticleController.java
  src/main/java/codesquad/springcafe/controller/ArticleForm.java
  src/main/java/codesquad/springcafe/controller/HomeController.java
  src/main/java/codesquad/springcafe/controller/MemberController.java
  src/main/java/codesquad/springcafe/controller/MemberForm.java
  src/main/java/codesquad/springcafe/domain/Article.java
  src/main/java/codesquad/springcafe/domain/Member.java
  src/main/java/codesquad/springcafe/domain/Profile.java
  src/main/java/codesquad/springcafe/repository/ArticleRepository.java
  src/main/java/codesquad/springcafe/repository/MemoryArticleRepository.java
  src/main/java/codesquad/springcafe/repository/MemoryMemberRepository.java
  src/main/java/codesquad/springcafe/repository/MemoryProfileRepository.java
  src/main/java/codesquad/springcafe/repository/ProfileRepository.java
  src/main/java/codesquad/springcafe/service/ArticleService.java
  src/main/java/codesquad/springcafe/service/MemberService.java
  src/main/resources/application.properties
  src/main/resources/static/form.html
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
Labels: Step7-2

#85 [주주] step-3 DB에 저장하기
  build.gradle
  src/main/java/codesquad/springcafe/controller/ArticleController.java
  src/main/java/codesquad/springcafe/controller/UserController.java
  src/main/java/codesquad/springcafe/model/Article.java
  src/main/java/codesquad/springcafe/model/User.java
  src/main/java/codesquad/springcafe/repository/ArticleRepository.java
  src/main/java/codesquad/springcafe/repository/JdbcArticleRepository.java
  src/main/java/codesquad/springcafe/repository/JdbcUserRepository.java
  src/main/java/codesquad/springcafe/repository/MemoryArticleRepository.java
  src/main/java/codesquad/springcafe/repository/MemoryUserRepository.java
  src/main/java/codesquad/springcafe/repository/UserRepository.java
  src/main/java/codesquad/springcafe/service/ArticleService.java
  src/main/java/codesquad/springcafe/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/templates/index.html
Labels: Step7-3

#93 [애셔] step-3 DB에 저장하기
  build.gradle
  src/main/java/codesquad/springcafe/web/controller/ArticleController.java
  src/main/java/codesquad/springcafe/web/domain/Article.java
  src/main/java/codesquad/springcafe/web/repository/ArticleRepository.java
  src/main/java/codesquad/springcafe/web/repository/JdbcTemplateArticleRepository.java
  src/main/java/codesquad/springcafe/web/repository/JdbcTemplateUserRepository.java
  src/main/java/codesquad/springcafe/web/repository/MemoryArticleRepository.java
  src/main/java/codesquad/springcafe/web/repository/MemoryUserRepository.java
  src/main/resources/application.properties
  src/main/resources/templates/article/form.html
  src/main/resources/templates/article/show.html
  src/main/resources/templates/index.html
  src/main/resources/templates/user/list.html
Labels: Step7-3

#97 [미르] Step-4 로그인 구현
  src/main/java/codesquad/springcafe/interceptor/Config.java
  src/main/java/codesquad/springcafe/interceptor/LoginInterceptor.java
  src/main/java/codesquad/springcafe/user/User.java
  src/main/java/codesquad/springcafe/user/UserController.java
  src/main/java/codesquad/springcafe/user/UserService.java
  src/main/java/codesquad/springcafe/user/database/UserJdbcRepository.java
  src/main/java/codesquad/springcafe/user/database/UserMemoryRepository.java
  src/main/resources/static/users/login.html
  src/main/resources/static/users/login_failed.html
  src/main/resources/templates/fragments/script.html
  src/main/resources/templates/fragments/subnav.html
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/users/form.html
  src/main/resources/templates/users/list.html
  src/main/resources/templates/users/login.html
  src/main/resources/templates/users/profile.html
  src/main/resources/templates/users/updateform.html
Labels: Step8-1

#100 [eddy] step-4 로그인 구현
  README.md
  build.gradle
  src/main/java/codesquad/springcafe/Controller/IndexController.java
  src/main/java/codesquad/springcafe/Controller/UserController.java
  src/main/java/codesquad/springcafe/Domain/User.java
  src/main/java/codesquad/springcafe/MvcConfig.java
  src/main/java/codesquad/springcafe/Repository/PostRepositoryJDBC.java
  src/main/java/codesquad/springcafe/Repository/UserRepository.java
  src/main/java/codesquad/springcafe/Repository/UserRepositoryImpl.java
  src/main/java/codesquad/springcafe/Repository/UserRepositoryJDBC.java
  src/main/java/codesquad/springcafe/Service/UserService.java
  src/main/resources/application.properties
  src/main/resources/sql/ddl.sql
  src/main/resources/templates/layout/navbar_right.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/update.html
Labels: Step8-1

#101 [데이] step-5 게시글 권한부여
  README.md
  src/main/java/codesquad/springcafe/DB/MyDatabase.java
  src/main/java/codesquad/springcafe/controller/ArticleController.java
  src/main/java/codesquad/springcafe/controller/UserController.java
  src/main/java/codesquad/springcafe/domain/Article.java
  src/main/java/codesquad/springcafe/domain/db/ArticleDatabase.java
  src/main/java/codesquad/springcafe/domain/repository/ArticleRepository.java
  src/main/java/codesquad/springcafe/domain/repository/UserRepository.java
  src/main/java/codesquad/springcafe/dto/EditArticleForm.java
  src/main/java/codesquad/springcafe/exception/NotFoundException.java
  src/main/java/codesquad/springcafe/exception/ResponseExceptionHandler.java
  src/main/java/codesquad/springcafe/interceptor/Config.java
  src/main/java/codesquad/springcafe/repository/H2ArticleRepository.java
  src/main/java/codesquad/springcafe/repository/H2UserRepository.java
  src/main/java/codesquad/springcafe/repository/MemoryArticleRepository.java
  src/main/java/codesquad/springcafe/repository/MemoryUserRepository.java
  src/main/java/codesquad/springcafe/service/AccessService.java
  src/main/java/codesquad/springcafe/service/ArticleService.java
  src/main/java/codesquad/springcafe/service/UserService.java
  src/main/java/codesquad/springcafe/service/validator/ArticleValidator.java
  src/main/java/codesquad/springcafe/service/validator/UserValidator.java
  src/main/resources/templates/article/editForm.html
  src/main/resources/templates/article/form.html
  src/main/resources/templates/article/show.html
  src/main/resources/templates/error/404.html
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/register/form.html
Labels: Step8-2

#102 [Zoonmy] Step 6 댓글
  README.md
  docs/STEP-6.md
  docs/img/img_5.png
  docs/img/img_6.png
  docs/img/img_7.png
  docs/img/img_8.png
  docs/img/img_9.png
  docs/img1/img.png
  docs/img1/img_1.png
  docs/img1/img_2.png
  docs/img1/img_3.png
  docs/img1/img_4.png
  docs/img1/img_5.png
  src/main/java/codesquad/springcafe/articles/controller/ArticleController.java
  src/main/java/codesquad/springcafe/articles/model/Reply.java
  src/main/java/codesquad/springcafe/articles/model/dto/ReplyCreationRequest.java
  src/main/java/codesquad/springcafe/articles/model/dto/ReplyViewDto.java
  src/main/java/codesquad/springcafe/articles/repository/ArticleRepository.java
  src/main/java/codesquad/springcafe/articles/repository/H2ArticleRepository.java
  src/main/java/codesquad/springcafe/articles/repository/MemoryArticleRepository.java
  src/main/java/codesquad/springcafe/articles/service/ArticleService.java
  src/main/java/codesquad/springcafe/db/ArticleDatabase.java
  src/main/java/codesquad/springcafe/exception/ArticleAccessException.java
  src/main/java/codesquad/springcafe/exception/ExceptionController.java
  src/main/java/codesquad/springcafe/exception/ReplyAccessException.java
  src/main/java/codesquad/springcafe/exception/ReplyNotFoundException.java
  src/main/resources/static/css/post/show.css
  src/main/resources/templates/article/show.html
  src/main/resources/templates/base/replyList.html
Labels: Step8-3

#103 [상추] Step-7 ajax 댓글 구현
  build.gradle
  sql/create.sql
  src/main/java/codesquad/springcafe/WebConfig.java
  src/main/java/codesquad/springcafe/advice/LoginUserAdvice.java
  src/main/java/codesquad/springcafe/controller/ArticleController.java
  src/main/java/codesquad/springcafe/controller/CommentApiController.java
  src/main/java/codesquad/springcafe/controller/HomeController.java
  src/main/java/codesquad/springcafe/controller/LoginController.java
  src/main/java/codesquad/springcafe/controller/UserController.java
  src/main/java/codesquad/springcafe/database/article/ArticleDatabase.java
  src/main/java/codesquad/springcafe/database/article/ArticleJdbcDatabase.java
  src/main/java/codesquad/springcafe/database/article/ArticleMemoryDatabase.java
  src/main/java/codesquad/springcafe/database/comment/CommentDatabase.java
  src/main/java/codesquad/springcafe/database/comment/CommentJdbcDatabase.java
  src/main/java/codesquad/springcafe/database/user/UserJdbcDatabase.java
  src/main/java/codesquad/springcafe/database/user/UserMemoryDatabase.java
  src/main/java/codesquad/springcafe/exception/ArticleHasCommentsException.java
  src/main/java/codesquad/springcafe/exception/ArticleNotFoundException.java
  src/main/java/codesquad/springcafe/exception/CommentNotFoundException.java
  src/main/java/codesquad/springcafe/exception/UserNotFoundException.java
  src/main/java/codesquad/springcafe/form/article/ArticleDeleteForm.java
  src/main/java/codesquad/springcafe/form/comment/CommentWriteForm.java
  src/main/java/codesquad/springcafe/form/user/LoginUser.java
  src/main/java/codesquad/springcafe/form/user/UserEditForm.java
  src/main/java/codesquad/springcafe/interceptor/ArticleAccessInterceptor.java
  src/main/java/codesquad/springcafe/interceptor/LoginCheckInterceptor.java
  src/main/java/codesquad/springcafe/interceptor/UserAccessInterceptor.java
  src/main/java/codesquad/springcafe/model/Article.java
  src/main/java/codesquad/springcafe/model/Comment.java
  src/main/java/codesquad/springcafe/model/User.java
  src/main/java/codesquad/springcafe/service/ArticleService.java
  src/main/java/codesquad/springcafe/service/CommentService.java
  src/main/java/codesquad/springcafe/service/LoginService.java
  src/main/java/codesquad/springcafe/service/UserService.java
  src/main/java/codesquad/springcafe/util/LoginUserProvider.java
  src/main/resources/application.properties
  src/main/resources/errors.properties
  src/main/resources/templates/article/delete.html
  src/main/resources/templates/article/show.html
  src/main/resources/templates/error/409.html
  src/main/resources/templates/home/index.html
  src/main/resources/templates/user/profile.html
  src/test/java/codesquad/springcafe/database/article/ArticleDatabaseTest.java
  src/test/java/codesquad/springcafe/database/comment/CommentDatabaseTest.java
  src/test/java/codesquad/springcafe/database/user/UserDatabaseTest.java
Labels: Step9-1

#104 [심바] step-3 DB에 저장하기
  build.gradle
  src/main/java/codesquad/UserProfileData.java
  src/main/java/codesquad/springcafe/controller/ArticleController.java
  src/main/java/codesquad/springcafe/controller/HomeController.java
  src/main/java/codesquad/springcafe/controller/UserController.java
  src/main/java/codesquad/springcafe/model/Article.java
  src/main/java/codesquad/springcafe/model/User.java
  src/main/java/codesquad/springcafe/repository/article/ArticleRepository.java
  src/main/java/codesquad/springcafe/repository/article/JdbcTemplateArticleRepository.java
  src/main/java/codesquad/springcafe/repository/article/MemoryArticleRepository.java
  src/main/java/codesquad/springcafe/repository/user/JdbcTemplateUserRepository.java
  src/main/java/codesquad/springcafe/repository/user/MemoryUserRepository.java
  src/main/java/codesquad/springcafe/repository/user/UserRepository.java
  src/main/resources/application.properties
  src/main/resources/static/qna/form.html
  src/main/resources/static/qna/show.html
  src/main/resources/static/user/form.html
  src/main/resources/static/user/list.html
  src/main/resources/templates/fragment/fragments.html
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/profile.html
Labels: Step7-3

#108 [웨이드] step-4 로그인 구현
  src/main/java/codesquad/springcafe/service/AuthService.java
  src/main/java/codesquad/springcafe/web/controller/AuthController.java
  src/main/java/codesquad/springcafe/web/dto/LoginDto.java
  src/main/resources/application.properties
  src/main/resources/templates/fragment/navbar.html
  src/main/resources/templates/index.html
  src/main/resources/templates/user/login.html
Labels: Step8-1
