Repository codesquad-members-2024/be-spring-cafe, pull requests merged in 2024-05, with the labels that each got.

#111 [이브이] step-5 게시글 권한부여
  src/main/java/codesquad/springcafe/config/WebConfig.java
  src/main/java/codesquad/springcafe/controller/ArticleController.java
  src/main/java/codesquad/springcafe/controller/HomeController.java
  src/main/java/codesquad/springcafe/controller/UserController.java
  src/main/java/codesquad/springcafe/domain/Article.java
  src/main/java/codesquad/springcafe/domain/User.java
  src/main/java/codesquad/springcafe/dto/ArticleDto.java
  src/main/java/codesquad/springcafe/dto/UserDto.java
  src/main/java/codesquad/springcafe/dto/UserUpdateDto.java
  src/main/java/codesquad/springcafe/error/ErrorExceptionHandler.java
  src/main/java/codesquad/springcafe/error/exception/AccessDeniedException.java
  src/main/java/codesquad/springcafe/error/exception/ArticleNotFoundException.java
  src/main/java/codesquad/springcafe/error/exception/UserNotFoundException.java
  src/main/java/codesquad/springcafe/interceptor/AuthorizationInterceptor.java
  src/main/java/codesquad/springcafe/repository/article/ArticleRepository.java
  src/main/java/codesquad/springcafe/repository/article/JdbcArticleRepository.java
  src/main/java/codesquad/springcafe/repository/article/MemoryArticleRepository.java
  src/main/java/codesquad/springcafe/repository/user/JdbcUserRepository.java
  src/main/java/codesquad/springcafe/repository/user/MemoryUserRepository.java
  src/main/java/codesquad/springcafe/repository/user/UserRepository.java
  src/main/java/codesquad/springcafe/service/ArticleService.java
  src/main/java/codesquad/springcafe/service/UserService.java
  src/main/resources/templates/article/page.html
  src/main/resources/templates/article/update.html
  src/main/resources/templates/error/page.html
  src/main/resources/templates/fragments/nav.html
  src/main/resources/templates/index.html
  src/main/sql/article.sql
  src/main/sql/users.sql
Labels: Step8-2

#112 [코리] Step-6 댓글 구현
  src/main/java/codesquad/springcafe/config/AppConfig.java
  src/main/java/codesquad/springcafe/controller/ArticleController.java
  src/main/java/codesquad/springcafe/controller/ErrorController.java
  src/main/java/codesquad/springcafe/controller/ReplyController.java
  src/main/java/codesquad/springcafe/controller/UserController.java
  src/main/java/codesquad/springcafe/exception/CannotDeleteArticleWithRepliesException.java
  src/main/java/codesquad/springcafe/exception/ReplyNotFound.java
  src/main/java/codesquad/springcafe/interceptor/LoginInterceptor.java
  src/main/java/codesquad/springcafe/model/Article.java
  src/main/java/codesquad/springcafe/model/Reply.java
  src/main/java/codesquad/springcafe/repository/ArticleJdbcRepository.java
  src/main/java/codesquad/springcafe/repository/ReplyJdbcRepository.java
  src/main/java/codesquad/springcafe/repository/ReplyRepository.java
  src/main/java/codesquad/springcafe/service/ArticleService.java
  src/main/java/codesquad/springcafe/service/ReplyService.java
  src/main/java/codesquad/springcafe/service/UserService.java
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/show.html
Labels: Step8-3

#118 [eddy] step-5 게시글 권한부여
  README.md
  src/main/java/codesquad/springcafe/Controller/PostController.java
  src/main/java/codesquad/springcafe/MvcConfig.java
  src/main/java/codesquad/springcafe/Repository/PostRepository.java
  src/main/java/codesquad/springcafe/SpringCafeApplication.java
  src/main/java/codesquad/springcafe/WebConfig.java
  src/main/java/codesquad/springcafe/controller/IndexController.java
  src/main/java/codesquad/springcafe/controller/PostController.java
  src/main/java/codesquad/springcafe/controller/UserController.java
  src/main/java/codesquad/springcafe/domain/Post.java
  src/main/java/codesquad/springcafe/domain/User.java
  src/main/java/codesquad/springcafe/interceptor/LoginInterceptor.java
  src/main/java/codesquad/springcafe/repository/PostRepository.java
  src/main/java/codesquad/springcafe/repository/PostRepositoryImpl.java
  src/main/java/codesquad/springcafe/repository/PostRepositoryJDBC.java
  src/main/java/codesquad/springcafe/repository/UserRepository.java
  src/main/java/codesquad/springcafe/repository/UserRepositoryImpl.java
  src/main/java/codesquad/springcafe/repository/UserRepositoryJDBC.java
  src/main/java/codesquad/springcafe/service/PostService.java
  src/main/java/codesquad/springcafe/service/UserService.java
  src/main/resources/sql/ddl.sql
  src/main/resources/static/css/post/show.css
  src/main/resources/templates/index.html
  src/main/resources/templates/post/form.html
  src/main/resources/templates/post/show.html
  src/main/resources/templates/post/update.html
  src/main/resources/templates/user/login.html
  src/test/java/codesquad/springcafe/repository/PostRepositoryImplTest.java
  src/test/java/codesquad/springcafe/repository/UserRepositoryImplTest.java
  src/test/java/codesquad/springcafe/service/UserServiceTest.java
Labels: Step8-2

#119 [미르] Step-5 게시글 권한부여
  src/main/java/codesquad/springcafe/error/advice/GlobalErrorHandler.java
  src/main/java/codesquad/springcafe/error/exception/ResourceNotFoundException.java
  src/main/java/codesquad/springcafe/interceptor/InterceptorConfig.java
  src/main/java/codesquad/springcafe/post/PostController.java
  src/main/java/codesquad/springcafe/post/PostService.java
  src/main/java/codesquad/springcafe/post/database/PostJdbcRepository.java
  src/main/java/codesquad/springcafe/post/database/PostMemoryRepository.java
  src/main/java/codesquad/springcafe/post/database/PostRepository.java
  src/main/java/codesquad/springcafe/user/UserController.java
  src/main/resources/application.properties
  src/main/resources/templates/error/404.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/qna/updatefail.html
  src/main/resources/templates/qna/updatepost.html
Labels: Step8-2

#120 [주주] step-4 로그인 구현
  src/main/java/codesquad/springcafe/controller/LoginController.java
  src/main/java/codesquad/springcafe/service/LoginService.java
  src/main/resources/application.properties
  src/main/resources/templates/fragment/navbar.html
  src/main/resources/templates/users/login.html
  src/main/resources/templates/users/login_failed.html
Labels: Step8-1

#123 [데이] step-6 댓글
  README.md
  src/main/java/codesquad/springcafe/controller/ArticleController.java
  src/main/java/codesquad/springcafe/controller/ReplyController.java
  src/main/java/codesquad/springcafe/domain/Article.java
  src/main/java/codesquad/springcafe/domain/Reply.java
  src/main/java/codesquad/springcafe/domain/repository/ArticleRepository.java
  src/main/java/codesquad/springcafe/domain/repository/DbRepository.java
  src/main/java/codesquad/springcafe/domain/repository/ReplyRepository.java
  src/main/java/codesquad/springcafe/domain/repository/UserRepository.java
  src/main/java/codesquad/springcafe/dto/EditReply.java
  src/main/java/codesquad/springcafe/dto/ReplyForm.java
  src/main/java/codesquad/springcafe/dto/ShowReply.java
  src/main/java/codesquad/springcafe/exception/InvalidAccessException.java
  src/main/java/codesquad/springcafe/exception/LoginFailException.java
  src/main/java/codesquad/springcafe/exception/NotFoundException.java
  src/main/java/codesquad/springcafe/exception/ResponseExceptionHandler.java
  src/main/java/codesquad/springcafe/repository/H2ArticleRepository.java
  src/main/java/codesquad/springcafe/repository/H2ReplyRepository.java
  src/main/java/codesquad/springcafe/service/ReplyService.java
  src/main/resources/templates/article/editReplyForm.html
  src/main/resources/templates/article/show.html
  src/main/resources/templates/error/invalidAccess.html
Labels: Step8-3

#125 [kalia] step-3 DB에 저장하기
  build.gradle
  src/main/java/codesquad/springcafe/Article/ArticleController.java
  src/main/java/codesquad/springcafe/Article/ArticleRepository.java
  src/main/java/codesquad/springcafe/Article/ArticleService.java
  src/main/java/codesquad/springcafe/Article/JdbcArticleRepository.java
  src/main/java/codesquad/springcafe/Article/MemoryArticleRepository.java
  src/main/java/codesquad/springcafe/Member/JdbcMemberRepository.java
  src/main/java/codesquad/springcafe/Member/Member.java
  src/main/java/codesquad/springcafe/Member/MemberController.java
  src/main/java/codesquad/springcafe/Member/MemberRepository.java
  src/main/java/codesquad/springcafe/Member/MemberService.java
  src/main/java/codesquad/springcafe/Member/MemoryMemberRepository.java
  src/main/java/codesquad/springcafe/SpringCafeApplication.java
  src/main/resources/application.properties
  src/main/resources/templates/article/show.html
  src/test/java/codesquad/springcafe/ArticleTest/ArticleControllerTest.java
  src/test/java/codesquad/springcafe/ArticleTest/MemoryArticleRepositoryTest.java
  src/test/java/codesquad/springcafe/MemberTest/MemberControllerTest.java
  src/test/java/codesquad/springcafe/MemberTest/MemoryMemberRepositoryTest.java
Labels: Step7-3

#129 [웨이드] step-5 게시글 권한부여
  src/main/java/codesquad/springcafe/domain/article/Article.java
  src/main/java/codesquad/springcafe/domain/article/ArticleRepository.java
  src/main/java/codesquad/springcafe/domain/article/JdbcArticleRepository.java
  src/main/java/codesquad/springcafe/domain/article/MemoryArticleRepository.java
  src/main/java/codesquad/springcafe/service/ArticleService.java
  src/main/java/codesquad/springcafe/web/WebConfig.java
  src/main/java/codesquad/springcafe/web/controller/ArticleController.java
  src/main/java/codesquad/springcafe/web/dto/ArticleCreateDto.java
  src/main/java/codesquad/springcafe/web/dto/ArticleUpdateDto.java
  src/main/java/codesquad/springcafe/web/interceptor/LogInterceptor.java
  src/main/java/codesquad/springcafe/web/interceptor/LoginCheckInterceptor.java
  src/main/java/codesquad/springcafe/web/validation/ArticleCreateValidator.java
  src/main/resources/templates/fragment/navbar.html
  src/main/resources/templates/fragment/script.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/qna/updateForm.html
Labels: Step8-2

#135 [Zoonmy] step-7 ajax 댓글 구현
  README.md
  build.gradle
  docs/STEP-7.md
  docs/img.png
  docs/img_1.png
  src/main/java/codesquad/springcafe/articles/controller/ArticleController.java
  src/main/java/codesquad/springcafe/articles/model/Article.java
  src/main/java/codesquad/springcafe/articles/repository/ArticleRepository.java
  src/main/java/codesquad/springcafe/articles/repository/DbArticleRepository.java
  src/main/java/codesquad/springcafe/articles/repository/MemoryArticleRepository.java
  src/main/java/codesquad/springcafe/articles/service/ArticleService.java
  src/main/java/codesquad/springcafe/config/interceptor/LoggedInInterceptor.java
  src/main/java/codesquad/springcafe/config/interceptor/LoggedOutInterceptor.java
  src/main/java/codesquad/springcafe/db/ArticleDatabase.java
  src/main/java/codesquad/springcafe/db/UserDatabase.java
  src/main/java/codesquad/springcafe/exception/ArticleCreationException.java
  src/main/java/codesquad/springcafe/exception/UnauthorizedException.java
  src/main/java/codesquad/springcafe/replies/controller/ReplyRestController.java
  src/main/java/codesquad/springcafe/replies/model/Reply.java
  src/main/java/codesquad/springcafe/replies/model/dto/ReplyCreationRequest.java
  src/main/java/codesquad/springcafe/replies/model/dto/ReplyViewDto.java
  src/main/java/codesquad/springcafe/replies/repository/DbReplyRepository.java
  src/main/java/codesquad/springcafe/replies/repository/ReplyRepository.java
  src/main/java/codesquad/springcafe/replies/service/ReplyService.java
  src/main/java/codesquad/springcafe/users/controller/UserController.java
  src/main/java/codesquad/springcafe/users/model/User.java
  src/main/java/codesquad/springcafe/users/model/dto/UserPreviewDto.java
  src/main/java/codesquad/springcafe/users/repository/DbUserRepository.java
  src/main/java/codesquad/springcafe/users/repository/MemoryUserRepository.java
  src/main/java/codesquad/springcafe/users/service/UserService.java
  src/main/java/codesquad/springcafe/utils/AuthValidateService.java
  src/main/resources/application.properties
  src/main/resources/sql/H2/Articles.sql
  src/main/resources/sql/H2/Replies.sql
  src/main/resources/sql/H2/Users.sql
  src/main/resources/sql/MySql/Articles.sql
  src/main/resources/sql/MySql/Replies.sql
  src/main/resources/sql/MySql/Users.sql
  src/main/resources/static/js/reply/reply-script.js
  src/main/resources/templates/article/show.html
  src/main/resources/templates/article/updateForm.html
  src/main/resources/templates/base/replyList.html
  src/main/resources/templates/base/replyPartial.html
  src/main/resources/templates/user/updateForm.html
Labels: Step9-1

#137 [데이] step-7 ajax 댓글 구현
  README.md
  build.gradle
  src/main/java/codesquad/springcafe/controller/ReplyRestController.java
  src/main/java/codesquad/springcafe/domain/Result.java
  src/main/java/codesquad/springcafe/domain/repository/DbRepository.java
  src/main/java/codesquad/springcafe/domain/repository/ReplyRepository.java
  src/main/java/codesquad/springcafe/dto/AjaxTemplateReply.java
  src/main/java/codesquad/springcafe/dto/ShowReply.java
  src/main/java/codesquad/springcafe/repository/H2ArticleRepository.java
  src/main/java/codesquad/springcafe/repository/H2ReplyRepository.java
  src/main/java/codesquad/springcafe/repository/H2UserRepository.java
  src/main/java/codesquad/springcafe/repository/MemoryArticleRepository.java
  src/main/java/codesquad/springcafe/repository/MemoryUserRepository.java
  src/main/java/codesquad/springcafe/service/ReplyService.java
  src/main/resources/application.properties
  src/main/resources/templates/article/show.html
Labels: Step9-1
